### ISSUE TITLE
Not creating public dns names to access the cluster over SSH

### ISSUE THREAD

**Issue by HariprasadAllaka1612** [cloudposse/terraform-aws-emr-cluster#9]
When creating the cluster using this script. I am not able to see the public dns host name that is required to ssh into the cluster

**Comment by aknysh** [comment]
@HariprasadAllaka1612 
in the outputs, we have:

https://github.com/cloudposse/terraform-aws-emr-cluster/blob/master/outputs.tf#L11 - the master endpoint generated by AWS

https://github.com/cloudposse/terraform-aws-emr-cluster/blob/master/outputs.tf#L26 - the CNAME that the module created in the provided DNS zone (if the zone was provided)

so you can use any of those to SSH to the master node.

It's better to use the CNAME since it should never change.
The generated endpoint will stay the same as long as you don't re-create the cluster. Once re-created, the endpoint will be changed by AWS

**Comment by aknysh** [comment]
see the complete working example https://github.com/cloudposse/terraform-aws-emr-cluster/tree/master/examples/complete

and the automatic test for the example https://github.com/cloudposse/terraform-aws-emr-cluster/blob/master/test/src/examples_complete_test.go

**Comment by HariprasadAllaka1612** [comment]
Master public DNS:
ip-xx-xx-x-xx.eu-central-1.compute.internal is getting created something like this when i am checking on AWS console.. is this something expected

**Comment by aknysh** [comment]
@HariprasadAllaka1612 
The endpoint looks good.
you can place the cluster in a public or private subnet.
If placed in a public subnet, you could SSH to it from the internet (if the security group allows it).
If placed in a private subnet, you can't access it from the internet on any port, you could only access it from a bastion host in the same VPC, or from the kubernetes nodes deployed in the same VPC
